# 导论

## 研究背景与研究意义

### 研究背景

近几年来，“富二代”“官二代”等词语一度比较火热，正所谓“龙生龙，凤生凤，老鼠的儿子会打洞”。这些热门词汇在一定程度上反映出我国社会可能存在着社会代际传递及阶层固化等问题。代际传递不仅反映在父母的收入和地位方面，还反映在教育方面，就是所谓的“学二代”。收入和地位较高的父母一般很重视子女的教育，并通过加强教育投资来提升子女的人力资本水平。教育人力资本是人力资本最重要的组成部分，对人力资本起着重大的影响，教育人力资本还会通过代际传递对子女的人力资本起到显著的影响。

教育强国是中华民族伟大复兴的基础工程。从建国以来，中国一直很注重教育，在教
育方面的投入也是与日俱增.2017 年,全国教育经费总投入为42562.01 亿元,同比增长9.45%。
其中，国家财政性教育经费为 34207. 75 亿元，同比增长 8.95%。2017 年全国国内生产总值
为 827122 亿元，国家财政性教育经费占国内生产总值比例为 4.14%。我国政府对教育的重
视程度可见一番。

从 1978 年改革开放到 2018 年，这四十年以来我国教育事业也取得巨大的进步。学前
教育三年毛入园率从 10.6%提升到 79.6%，小学学龄儿童净入学率从 94%提升到 99.9%%，初中
阶段毛入学率从 66.4%提升到 103.8，高中阶段毛入学率从 33.6%提升到 88.3%，高等教育
毛入学率从 2.1%提升到 45.7%，均达到或超过中高收入国家平均水平。

另一方面，在中国教育规模不断增大的情况下，也存在涛教育不公平的现象，比如“学
二代”。“学二代” 现象主要说明，父母拥有较高的受教育水平很大程度上会使得他们的子女
同样拥有较高的受教育水平,这就形成了在受教育水平上的一种代际传递。这种代际传递在
一定程度呈现出“教育垄断”的现象。同样的，父母的受教育水平如果比较低的话，孩子的
受教育水平很大程度会受到影响, 子女接受到较高水平教育的可能性会降低。 而教育是摆脱
贫困的一种非常重要的途径, 是社会阶层向上流动的利器。 教育的不平等现象会加剧社会阶
层固化现象，导臻“寒门难出贵子”，不利于社会的稳定。因此教育的代际传递不仅反映出
教育方面的现象，也一定程度上反映出社会的阶层固化现象。


### 研究意义

#### 理论意义

教育人力资本投资作为人力资本投资重要组成部分，受教育程度的高低很大程度可以衡量人力资本的存量水平。从教育人力资本的代际传递状况一定程度上可以看出教育的代际流动性水平，因为教育的代际传递性和教育的代际流动性呈现反向关系。教育的代际传递性较强说明教育的代际流动性较弱，会产生教育不公平的社会矛盾；教育的代际传递性较弱说明教育的代际流动性较强，有利于社会阶层之间的流动。从以往的经验来看，父母的受教育水平对女子的受教育水平有比较显著的正向影响。本文利用微观数据来具体研宄父母的受教育水平对子女的受教育水平的影响，并分析这种影响是否为正，大概有多大，在不同地区、城乡之间、户籍、性别等方面是否存在差异，并利用相关的理论进行实证分析。


#### 现实意义

教育是一国之本，为一个国家创造出高素质人才提供源源不断的动力。“知识改变命运”一直被普遍流传，成为很多人读书的动力，尤其是基层人民群众。对于基层人民群众而言，通过高考进入大学可以说是改变命运的最重要途径之一，也是一条改变人生的捷径，甚至对一些落后地区的人来说可能是唯一的途径。知识改变命运，改变的不止是一个人命运，可能是一个家庭或者整个后代的命运。因为个人命运的改变会通过教育的代际传递，为子女提供更好的教育资源和更多的教育机会，提高子女的人力资本水平，并形成一种良性循环。对于国家而言，我国教育整体水平发展非常迅猛，下到义务教育的普及，上到高等教育的快速发展。随着大学的扩招，每年的应届毕业生人数不断增加，从大学生很稀少，到 2018 年高校毕业人数达到 820 万人`。曾经稀奇的大学生，如今早已遍地开花。大学本科学历已经成为
很多用人单位招聘的基本条件，可见我国教育事业的飞速发展。但是与此同时,我国也存在
着教育机会不平等的现象， 尤其是在高等学府，存在着较为严重的城乡户籍差异。据相关数
据统计，2016 年北京大学新增 3363 名本科生，其中农村户籍的本科生比例仅占 16.3%，这
还是包括一些北京大学对落后地区的农村学生专项计划招生, 也就是对落后地区的政策照顾。
如果只计算以高考成绩录取的，那么农村户籍的本科生所占比例不足一成。但是在 1978 年
至 1998 年这段时间，北京大学每年录取新生中，农村户籍的比例高达 30%。 在中国高校大
规模的扩招之后, 农村户籍的大学生数量虽然也不断增多, 但是和城市相比整体质量并不高。
农村户籍的大学生很大一部分是在实力较红的地方普通院校或者是专科院校, 而城市户籍的
大学生在重点院校的比例较高这种现象也一定程度上反映出目前整体的教育代际流动性减
弱, 教育的代际传递性增强。目前我国的教育水平还存在区域差距和城乡之间的差异，主要
是因为一个地区的经济水平和教育水平是相互促进的。经济发达的地区会增加对教育经费的
投入，而教育经费投入的增多，会提高该地区的人力资本水平，反过来促进经济的增长，形
成一种良性循环。 因此研究教育的代际传递和代际流动性，研究教育机会的不平等现象，臻
力于为政府提出适宜的宏观调控政策, 呼吁政府对这种现象的重视。这种研究有利于增强教
育代际的流动性, 也利于社会阶层之间的流动, 从而缓解社会阶层固化现象, 减轻社会矛盾，
维护社会稳定，促进我国经济又快又好的稳定发展。


## 研宄方法与论文结构

### 研宄方法

本文主要研究教育人力资本和教育的代际传递这两个方面，归纳了之前国内外的学者对教育的代际传递和教育的代际流动等方面的相关文献，形成一定的理论基础，通过实证分析，探讨了教育人力资本的代际传递的状况及影响因素，并分析了教育的代际传递在性别、城乡户籍、东中西部、70后与80后、父母教育匹配情况等方面的差异。

#### 文献分析法


本文通过搜集大量的国内外关于教育人力资本的代际传递等相关理论及文献，尤其是中国的相关文献。因为中国的教育代际传递状况具有其自身特点，尤其是在家庭教育方面，受传统文化的影响，中国的家庭观念更浓，更注重对下一代的关注和培养。通过分析文献，为本文进一步分析和研究提供了很多借鉴和参考。


#### 统计分析法


统计分析法主要是基于数据本身的统计特点，本文主要包括描述性统计和教育代际转换矩阵分析，描述性统计包括整体的观测值、均值、标准差、最小值和最大值，还包括在父母之间受教育水平的匹配度，子女受教育水平在性别、城乡户籍、东中西部、70后与80后等方面的具体分析。教育代际转换矩阵分析主要是基与具体分布的比例形成的概率统计，更好地分析教育人力资本的代际流动性特点。


#### 计量分析法

计量方法是经济学进行实证研宄的主要方法。为了更好的研宄教育人力资本的代际传递，本文运用了学术界较为认可的微观家庭数据---2016年的中国家庭追踪调査数据（CFPS），基于数据特征，采用有序logit模型进行具体的分析。包括整体回归结果的分析及各变量回归结果的解释，和具体的分样本分析，比如父母的受教育水平对子女受教育水平的影响在性别、城乡户籍、东中西部、70后与80后等方面的是否存在差异进行具体的回归分析，并讨论父母之间的教育匹配程度对子女的受教育水平的影响。


### 论文结构
本文的研究内容分为五个章节:

第一章是导论。主要包含本文的研究背景与研究意义，然后是论文的研究方法与论文
的结构设计，最后是本文可能的创新及不足之处。

第二章是相关的理论及文献综述，理论主要包括人力资本理论、教育人力资本理论、
盖茨比曲线和教育的代际传递理论，其中包含“MMI”和“EMI”理论。之后归纳梳理了一些
国内外的相关研究文献。

第三章是数据说明及描述性统计分析，数据说明包括数据来源及变量说明，描述性统
计包括整体的观测值、均值、标准差、最小值和最天值，还包括在父母之间受教育水平的匹
配度，子女受教育水平在性别、城乡户籍、东中西部、70 后与 80 后等方面的具体分析。

第四章是实证分析，采用 2016 年的中国家庭追踪调查数据(CEPS) 进行分析，包括教育代际转换矩阵分析和有序 logit 回归分析。对整体样本回归和具体的分样本同归分析，包
括父母的受教育水平对子女受教育水平的影响在性别、城乡户籍、东中西部、70 后与 80 后
等方面的是否存在差异进行具体的回归分析, 并讨论父母之间的教育匹配程度对子女的受教
育水平的影响。

第五章是论文的结论和相关的政策建议。总结本文的研究结论，并基于此提出相应的政策及建议。

### 可能的创新与不足

#### 可能的创新

第一, 本文在分析父母的受教育程度对子女的受教育水平的影响的同时，也分析了父母
婚姻之间的教育匹配程度对子女的影响，即婚姻教育方面的“门当户对”

第二, 不同于以往的教育代际的视角, 本文加入了人力资本及教育人力资本的相关理论
研究，能更好地体现出教育在本质上是一种投资行为。

第三，本文用比较权威的微观数据一一2016 年中国家庭追踪调查数据作为研究分析，
更具有代表性与说服力，并加入盖茨比曲线等方面的理论，展现出中国的阶层固化现象。

第四，本文在有序 logit 回归中，不仅对整体样本进行回归分析，还分别对性别、城乡
户籍、东中西部、70 后与 80 后等方面进行较为详细地分析，并对五个级别学历的边际效应
进行分析。

####  不足之处

第一，在对教育人力资本代际传递的分析模型中，只是单纯分析了学历上的差异,忽视
了相同学历水平在质量方面的差别，比如普通中学和重点中学的差异,普通大学和重点大学
之间的差异等。

第二, 本文虽然对教育人力资本的代际传递进行了一定的理论及实证分析, 但由于数据、
方法及作者本身水平等方面的限制,本文对代际流动背后的复杂机制缺乏更加深入的探讨和
研究。
