# 结论及政策建议
    
## 结论

本文采用 2016 年的中国家庭追踪调查数据 (CFPS)，来对教育人力资本的代际传递问
题进行研究，在相关理论基础上，主要运用描述性统计、教育代际转换矩阵和有序 logit 回
归进行实证分析， 不仅对整体样本进行回归分析, 还对样本进行分类分析, 包括教育的代际
传递在性别、城乡户籍、东中西部、70 后与 80 后、父母教育匹配情况等方面的差异进行分
析。主要结论包插以下几点:

1、父母的受教育程度对子女的受教育水平有显著的正向影响，当父亲的受教育程度提
高一个级别时，其子女的受教育水平向上提高一个级别的概率会增加 53.24%，当母亲的受
教育程度提高一个级别时，其子女的受教育水平向上提高一个级别的概率会增加 55. 95%。
母亲相对父亲影响作用更大,母亲的受教育水平提高时, 子女处于低水平学历的概率减少的
更多，处于高水平的学历的概率增加的更大。主要原因可能是在中国传统文化的影响下,家
庭内部，父亲更多的主外，母亲更多的主内。在一般的家庭中，母亲相对承担更多的教育子
女以及家庭事务，子女一般和母亲的相处时间更长，受母亲的教育影响更大。

2、从父母的受教育水平之间的匹配程度来看，当父母的受教育水平一臻时，父母的整
体受教育水平每提高一个级别，子女的受教育水平提高一个级别的可能性增加 53. 37%:，当
父母的受教育水平不一致时,父母的整体受教育水平每提高一个级别, 子女的受教育水平提
高一个级别的可能性增加 48.19%。可以看出，家庭婚姻的教育匹配更有利于子女的受教育
水平的提高。家庭婚姻的教育相互匹配，一方面利于家庭内部地位的相互平等,父母双方相
对能够更加和谐的生活，能够为子女提供一个良好的生活环境。另一方面，父母教育的相互
匹配，能够让父母在子女教育问题上更好地达成一致性，利于对子女的教育。

3、从子女的性别差异来看，当父母的整体受教育程度提高时，女性的受教育水平向上
提高一个级别的概率更大, 而且女性接受高等教育的可能性也更大。可能由于男性和女性在
生理和心里等方面存在差异，女性成熟的更早。从开始接受教育之初， 与同龄女孩相比，男
孩就已经答在了起跑线。而中国的教育基本上是一步落后步步落后,上不了重点初中就很难
考上重点高中,上不了重点高中就很难考上重点大学, 女性的优势会在小学开始不断地积累
和延续下去。

4、从城乡户籍差异来看, 与城市户籍相比, 农村户籍的父母教育程度提高一个级别时，
其子女的受教育水平向上提高一个级别的可能性更大, 农村地区的教育代际传递性比城市地
区更强，也就是说农村地区的教育代际流动性较低，教育不公平现象更加严重。而且在高等
教育方面, 城市户籍子女接受高等教育的可能性比农村户籍子女更高。主要因为农村地区的
教育资源相对缺乏, 子女的受教育水平更依赖于父母的受教育程度, 但农村地区父母的受教
育程度普遍偏低，这种过高的依赖性反而产生不利影响。农村地区的教育代际流动性较低，
阶层国化现象更为严重。

5、从不同地区来看，在教育代际传递性方面，西部地区最强，其次是中部地区，东部
地区最弱。但是在高等教育方面，东部地区的子女接受高等教育的机会最高，其次是中部地
区，西部地区的机会最少。教育代际流动性由东部、中部到西部地区依次递减，教育不公平
性也由东部、中部到西部地区递增。经济越落后的地区，教育不公平性反而越高。主要因为
落后地区教育资源总体上比较缺乏, 使得这部分资源主要集中在优势阶层中, 这种现象加剧
了“贫困代际传递” 落后地区形成一种恶性循环。

6、从出生年份来看，70 后的父母与其之间的教育代际传递性高于 80 后的父母与其之
间。但是在高等教育方面，80 后接受高等教育的机会高于 70 后。说明随着我国教育事业的
发展, 教育代际流动性增强，整体的教育不公平现象降低，但是这种降低主要集中在基础教
育方面，在高等教育方面，教育不公平性现象反而加剧。


## 政策建议

1、政府应统筹好城乡教育资源的均衡配置，促进城乡之间的教育公平。目前农村地区
的教育质量整体上比较差，导致农村地区学生的成绩整体上也比较差，很难考上重点中学。
很多农村地区的孩子只是完成义务教育就外出打工, 因为这些孩子在非义务教育阶段的考试
成绩和城市地区的孩子差距较大, 学习自信心受挫加上家庭本来也不富裕,就想尽早外出打
工挣钱。我国应该加强农村地区的教育投资,尤其是落后地区， 不仅提供好的教育设施及环
境， 后的农村家庭也能享受到优秀教师的裁培。

2、深化城乡户籍制度改革，减轻户籍对适龄儿童的教育歧视。要保障非城市户籍人群
在城市地区的受教育机会,这部分人群主要是外出打工的农民工子女,他们同样为城市的发
展做出巨大贡献。但是子女在受教育权利方面却存在不公平现象, 不仅很难上一些质量较好
的学校, 还要承担更多额外的教育费用，因此建议深化城乡户籍制度改革，取消借读费和转
学费等不合理的费用，使农民工子女能够享受到公平的教育权利。

3、加强对中西部地区教育经费的投入。和东部地区相比，中西部的教育相对落后，教
育代际流动性更低，尤其是西部地区。政府要保障落后地区及贫困家庭子女的受教育权利，
细化相关精准扶贫政策, 使教育经费支出更加公平合理。同时要保障教育经费的详细支出公
开透明化, 使教育经费真正落实下来。应该减轻居住区域及户籍等方面对公共教育资源配置
的影响,让基层群众的子女能够有更多的机会获得优质教育资源。在高等教育方面，让生活
补助和助学贷款等资助更多地绪盖到贫困家庭, 减轻贫困家庭的经济压力, 让教育真正成为
社会阶层流动的利器。




